# Eclipse
lang: EN
monochromeMode: false

spawn:
  world: spawn
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

  join:
    title: "&6&k|||&r &6Server &k|||"
    subtitle: "&fHave a nice game!"
    fadeIn: 25
    stay: 50
    fadeOut: 25
  respawn:
    title: "You died!"
    subtitle: "&aRevived!"
    fadeIn: 25
    stay: 25
    fadeOut: 25