name: Eclipse
version: "${version}"
main: me.catst0day.Eclipse.Eclipse
api-version: 1.13
website: https://github.com/CatsT0day/EclipseAPI/
softdepend:
  - luckperms
description: Server manager and api
author: CatsTOday

commands:
  eclipse:
    description: Main commands of the plugin
    permission: catapi.main

permissions:
  capi.main:
    description: gives perm to use main command (not all cmds)
  capi.update.notify:
    description: Receive update notifications for updates
    default: op
  eclipse.damage.fly.bypass:
    description: ...
    default: op
